#!/usr/bin/env bash
# Regenerates nginx/cloudflare-realip.conf from Cloudflare's published ranges.
# Cloudflare adds ranges occasionally; re-run this and reload nginx when they do.
set -euo pipefail

out="$(dirname "$0")/../nginx/cloudflare-realip.conf"

{
  echo "# Generated by scripts/update-cloudflare-ips.sh on $(date -u +%Y-%m-%d)"
  echo "# Restores the visitor's address from CF-Connecting-IP so rate limiting"
  echo "# and logging see real clients rather than Cloudflare's edge."
  echo
  curl -fsS https://www.cloudflare.com/ips-v4 | sed 's/^/set_real_ip_from /; s/$/;/'
  curl -fsS https://www.cloudflare.com/ips-v6 | sed 's/^/set_real_ip_from /; s/$/;/'
  echo
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$out"

echo "wrote $out"
